### ISSUE TITLE
Getting error when trying to split Korean Glossika

### ISSUE THREAD

**Issue by RpiDude** [chickendude/GlossikaNativeGLS#10]
I'm getting:

Checking 'texts/GLOSSIKA-ENKR-F2-EBK.pdf'
Traceback (most recent call last):
  File "./split_text.py", line 389, in <module>
    split()
  File "./split_text.py", line 385, in split
    split_text('', glob.glob(location), 'output', '')
  File "./split_text.py", line 368, in split_text
    book_info = BOOKS[language_pair]
KeyError: 'ENKR'

Is there no support for Korean Glossika?

**Comment by jubalh** [comment]
If you read https://github.com/chickendude/GlossikaNativeGLS/blob/master/split_text.py you can see that there is no Korean (KR) inside.
You can look at what is done for the other courses so far and adapt it to work with ENKR. Just add the ENKR symbols and the correct page numbers.

**Comment by RpiDude** [comment]
Never mind I managed to get Glossika Korean to convert by just adding EN, KR to entries inside:

split_audio.py
split_gms.py
split_text.py
create_gls.py

And it works beautifully!

You should really get https://f-droid.org/en/ to host this app so more people can discover it, thanks to chickendude for your great work!.

**Comment by jubalh** [comment]
> Never mind I managed to get Glossika Korean to convert by just adding EN, KR to entries inside:
split_audio.py
split_gms.py
split_text.py
create_gls.py

Then please create a pull request so that other users can benefit from it.

> You should really get https://f-droid.org/en/ to host this app so more people can discover it, thanks to chickendude for your great work!.

I think Natibo is not deemed ready yet, that's why it's not there.
